print("*** Your Adventure Simulator! ***")
print("You will be asked a bunch of amazing questions, and we will create an awesome story with YOU as the Protagonist of the story! We will customize the story to suit your own interests")
name = input("Enter your name : ")
family = input("Enter your family members' names: ")
friends = input("Enter your friends'names : ")
pets = input("Enter your pet or pets' names: ")
enemy = input("Enter your worst enemy's name: ")
skills = input("Enter your skills: ")
race = input("Enter your race: ")
hobbies = input("Enter your hobbies: ")
print()
print("Our story begins as our protagonist name walks into an empty Island !")
print("Suddenly, out of no where, a thin,tall man with walking sticks, wearing torn jeans and t-shirts, walks upto you and shouts out your", name)
print("You are shocked as to how this stranger",enemy, "knows you and is able to call your",name, "and he is really screaming out at the top of his voice", name,name,name)
print()
print("Oh no, you miss your", family, "and", friends, "and", pets, "so much now and wish they were with you  now, on this empty island ")
print()
print("The stranger", enemy, "is so weird that he even has the audacity to ask you what is your",  race, "and details about my","about my hobbies", hobbies, "and my skills", skills)
print()
print("I am gonna escape from this crazy island using my", hobbies, "and", skills, enemy, "clearly in the dark about my abilities in", skills, "and also ignorant about my expert\033[35m", skills,"\033[0min driving away my worst",enemy)
